### ISSUE TITLE
Setup main editor GUI & minimal parser structure

### ISSUE THREAD

**Issue by JeongHoJeong** [kernel-scape/MasterDown-webapp#11]
Minimal requirements:
- Text editing
- Realtime sync between editor & previewer

**Comment by JeOhLee** [comment]
For now, since we need to build parser first, AST viewer seems more useful than previewer. Maybe we need issue about designing AST class.

**Comment by JeongHoJeong** [comment]
I divided this issue into two smaller issues with more specific domain of problem. I'm closing this issue.
