### ISSUE TITLE
Conventions

### ISSUE THREAD

**Issue by JeOhLee** [kernel-scape/MasterDown-webapp#6]
Is there any convention we should make up? I found these

---------------
* TypeScript - [Coding Guidelines from MS](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines)
* Go lang - [Effective Go](https://golang.org/doc/effective_go.html)

--------------
Any other suggestion and comments?

**Comment by JeongHoJeong** [comment]
Let's discuss conventions throughout code review & debates.

**Comment by JeOhLee** [comment]
👍
